promptToReturnFromSubprocess: false
notARepository: skip

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
    mainBranches:
    - master
    - main
    - develop

os:
  editPreset: "nvim"


gui:
  sidePanelWidth: 0.18
  tabWidth: 2
  nerdFontsVersion: "2"
